dist: trusty
language: minimal
branches:
  only:
    - master

services:
  - docker

env:
  global:
    - VERSION=${TRAVIS_BUILD_NUMBER}

before_install:
  - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD} ${DOCKER_REGISTRY}

install:
  - make build

deploy:
  provider: script
  script:
    - make push
  on:
    branch: master
