name: CI

on:
  pull_request:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: Run checks and build
    runs-on: [self-hosted, bear]

    steps:

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GH_TOKEN }}

#      - name: Registry login
#        run: docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Docker build
        run: make build
        env:
          version: ${{ steps.get_version.outputs.VERSION }}

#      - name: Docker push
#        run: make push
